---
title: Jeffrey Silverstein
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: posts
    thumbnail-image: 
    external-url: 
    genre: 
    is-featured: 
permalink: none
email: jeffreylewissilverstein@gmail.com
description: |
  Jeffrey Silverstein is a writer, musician, and teacher living and working in Brooklyn, NY.
  tag_page_layout: tag_page tag_page_dir: tag tag_permalink_style: pretty
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
